spring:
  datasource:
    url: ${SPRING_DATASOURCE}/csp_demo
    username: ${SPRING_DATASOURCE_U}
    password: ${SPRING_DATASOURCE_P}
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect